repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
