# Test your FastAPI endpoints

@user_id_1 = "c2daaf1e-b373-49e2-94f3-1a55ff80b0d1"
@user_id_2 = "a6883ad9-794e-4ba9-903a-eed539b84677"

### Create Task
POST http://127.0.0.1:8000/tasks?user_id={{user_id_1}}
Accept: application/json

{
   "name": "Dishes",
   "status": "Blocked"
}

> {%
console.log(response.body.data.id)

client.global.set("task_id", response.body.data.id);
%}

### Get Task

GET http://127.0.0.1:8000/tasks/{{task_id}}?user_id={{user_id_1}}
Accept: application/json

### Get Task of a Different User

GET http://127.0.0.1:8000/tasks/{{task_id}}?user_id={{user_id_2}}
Accept: application/json

### Get Tasks

GET http://127.0.0.1:8000/tasks/?user_id={{user_id_1}}

Accept: application/json

### Get Tasks of a Different User

GET http://127.0.0.1:8000/tasks/?user_id={{user_id_2}}

Accept: application/json

### Update Task

PUT http://127.0.0.1:8000/tasks/{{task_id}}?user_id={{user_id_1}}
Accept: application/json

{
  "id": "{{task_id}}",
  "name": "Wash & Dry Dishes",
  "status": "Done",
  "due_date": null,
  "labels": [],
  "sub_tasks": []
}

### Delete Task of a Different User

DELETE http://127.0.0.1:8000/tasks/{{task_id}}?user_id={{user_id_1}}
Accept: application/json

### Delete Task of a Different User

DELETE http://127.0.0.1:8000/tasks/{{task_id}}?user_id={{user_id_2}}
Accept: application/json

